### ISSUE TITLE
[testfpga] ERROR: entry in lengths[i] is zero

### ISSUE THREAD

**Issue by JulyJohn** [dicecco1/fpga_caffe#7] opened 2017-11-23 12:46 UTC
I finally can't make it in the last [issue](https://github.com/dicecco1/fpga_caffe/issues/5).

But, after changes like following:
 1. Change the OS from Centos7 to CentOS6.5
 2. Change the SDAccel from 2017.1 to 2016.3
 3. Change the protobuf to 2.4.1

I compiled the fpga_caffe project successfully.

Then I run the "make testfpga", it was OK.

Then I try to test whether the testfpga work fine, so I go to the ./build_release/testfpga, and run a command like below, but it seems like that only the PCIeBandwidthTest is OK, others all failed due to an erro "ERROR: entry in lengths[i] is zero", finally ends up with "Segmentation fault (core dumped)".

```
[root@localhost testfpga]# XCL_EMULATION_MODE=true ./test_all.bin 
[==========] Running 25 tests from 9 test cases.
[----------] Global test environment set-up.
[----------] 6 tests from PCIeBandwidthTest/0, where TypeParam = OCLDevice<float>
[ RUN      ] PCIeBandwidthTest/0.TestSetup
[       OK ] PCIeBandwidthTest/0.TestSetup (5 ms)
[ RUN      ] PCIeBandwidthTest/0.TestBurst
[       OK ] PCIeBandwidthTest/0.TestBurst (60 ms)
[ RUN      ] PCIeBandwidthTest/0.TestBurst2
[       OK ] PCIeBandwidthTest/0.TestBurst2 (71 ms)
[ RUN      ] PCIeBandwidthTest/0.TestPadBurst
[       OK ] PCIeBandwidthTest/0.TestPadBurst (138 ms)
[ RUN      ] PCIeBandwidthTest/0.TestByChannel
[       OK ] PCIeBandwidthTest/0.TestByChannel (85 ms)
[ RUN      ] PCIeBandwidthTest/0.TestLocalBandwidth
ERROR: entry in lengths[i] is zero
Segmentation fault (core dumped)
```
After that, I run the "make test" to generate common test, and then I run the "make runtest".

Things seems all right until it comes to "BlobSimpleTest"

```
[----------] 5 tests from BlobSimpleTest/0, where TypeParam = float
[ RUN      ] BlobSimpleTest/0.TestPointersCPUOCL
ERROR: clCreateBuffer
*** Aborted at 1511440095 (unix time) try "date -d @1511440095" if you are using GNU date ***
PC: @     0x7fd979c913ef clEnqueueReadWriteBuffer()
*** SIGSEGV (@0x20) received by PID 26980 (TID 0x7fd97c893940) from PID 32; stack trace: ***
    @     0x7fd9784497e0 (unknown)
    @     0x7fd979c913ef clEnqueueReadWriteBuffer()
    @     0x7fd979c9397f clEnqueueWriteBuffer
    @     0x7fd978cb7eaa caffe::SyncedMemory::ocl_data()
    @     0x7fd978ca1c51 caffe::Blob<>::ocl_data()
    @           0x5ea1c5 caffe::BlobSimpleTest_TestPointersCPUOCL_Test<>::TestBody()
    @           0x7dc1ed testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x7d4791 testing::Test::Run()
    @           0x7d4876 testing::TestInfo::Run()
    @           0x7d49b7 testing::TestCase::Run()
    @           0x7d4d1e testing::internal::UnitTestImpl::RunAllTests()
    @           0x7dbd6d testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x7d3dee testing::UnitTest::Run()
    @           0x4d5cc5 main
    @     0x7fd9780c4d1d __libc_start_main
    @           0x4d59bd (unknown)
make: *** [runtest] Segmentation fault (core dumped)
```
So, can you provide some suggestion? :-)

**Comment by dicecco1** [comment] 2017-11-23 13:15
Some progress is good to hear!

I think I've since updated the bandwidth specific test, the issue is related to the expected name of the kernel which was changed recently to simplify the build flow. Basically all other tests pass because they're just testing PCIe transfer times without actually using a specific kernel, while the last test is for testing moving data from on-chip DDR to local BRAMs and back with different burst sizes. So if you grab the latest test file from the repo this error should go away. 

As for the other error you have, I'm guessing it's related to some of the OCL setup that happens in src/caffe/common.cpp Caffe::SetOCLDevice(). Unfortunately I haven't added much in terms of error checking here yet, so I recommend just going there and checking what the status variables are at each spot.

**Comment by dicecco1** [comment] 2017-11-23 13:48
I've updated a few of the tests that were failing or may fail because of outdated kernel names. I've also added some simple logging for errors in SetOCLDevice(), so grab the latest updates and try it out :)

**Comment by JulyJohn** [comment] 2017-11-24 07:26
Hi, @dicecco1 

Thanks for your reply so quickly. :-)

I have pulled the latest repo and compiled it again, but when I try to test the standlone fpga_test, it still gives the same erro:

```
[root@localhost testfpga]# XCL_EMULATION_MODE=true ./test_all.bin 
[==========] Running 25 tests from 9 test cases.
[----------] Global test environment set-up.
[----------] 6 tests from PCIeBandwidthTest/0, where TypeParam = OCLDevice<float>
[ RUN      ] PCIeBandwidthTest/0.TestSetup
[       OK ] PCIeBandwidthTest/0.TestSetup (9 ms)
[ RUN      ] PCIeBandwidthTest/0.TestBurst
[       OK ] PCIeBandwidthTest/0.TestBurst (71 ms)
[ RUN      ] PCIeBandwidthTest/0.TestBurst2
[       OK ] PCIeBandwidthTest/0.TestBurst2 (60 ms)
[ RUN      ] PCIeBandwidthTest/0.TestPadBurst
[       OK ] PCIeBandwidthTest/0.TestPadBurst (88 ms)
[ RUN      ] PCIeBandwidthTest/0.TestByChannel
[       OK ] PCIeBandwidthTest/0.TestByChannel (90 ms)
[ RUN      ] PCIeBandwidthTest/0.TestLocalBandwidth
ERROR: entry in lengths[i] is zero
Segmentation fault (core dumped)
```

Besides, I find another intresting thing, when I run 'make all', it seems that the layers in ['src/fpga_caffe/layers'](https://github.com/dicecco1/fpga_caffe/tree/master/src/fpga_caffe/layers) doesn't compile automaticlly.  Does it mean that I should compile those fpga layers manually?

Here are my 'make all' logs: 

```
[root@localhost fpga_caffe]# make all
PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/net.cpp
CXX src/caffe/layer_factory.cpp
CXX src/caffe/layer.cpp
CXX src/caffe/parallel.cpp
CXX src/caffe/blob.cpp
CXX src/caffe/syncedmem.cpp
CXX src/caffe/solvers/nesterov_solver.cpp
CXX src/caffe/solvers/sgd_solver.cpp
CXX src/caffe/solvers/adam_solver.cpp
CXX src/caffe/solvers/adadelta_solver.cpp
CXX src/caffe/solvers/adagrad_solver.cpp
CXX src/caffe/solvers/rmsprop_solver.cpp
CXX src/caffe/solver.cpp
CXX src/caffe/common.cpp
CXX src/caffe/util/upgrade_proto.cpp
CXX src/caffe/util/db_leveldb.cpp
CXX src/caffe/util/cudnn.cpp
CXX src/caffe/util/hdf5.cpp
CXX src/caffe/util/im2col.cpp
CXX src/caffe/util/insert_splits.cpp
CXX src/caffe/util/db_lmdb.cpp
CXX src/caffe/util/blocking_queue.cpp
CXX src/caffe/util/math_functions.cpp
CXX src/caffe/util/benchmark.cpp
CXX src/caffe/util/signal_handler.cpp
CXX src/caffe/util/io.cpp
CXX src/caffe/util/db.cpp
CXX src/caffe/data_transformer.cpp
CXX src/caffe/internal_thread.cpp
CXX src/caffe/layers/silence_layer.cpp
CXX src/caffe/layers/dropout_layer.cpp
CXX src/caffe/layers/log_layer.cpp
CXX src/caffe/layers/base_data_layer.cpp
CXX src/caffe/layers/hwcn_layer.cpp
CXX src/caffe/layers/input_layer.cpp
CXX src/caffe/layers/cudnn_relu_layer.cpp
CXX src/caffe/layers/XCL_program_layer.cpp
CXX src/caffe/layers/flatten_layer.cpp
CXX src/caffe/layers/cpfp_conversion_layer.cpp
CXX src/caffe/layers/softmax_loss_layer.cpp
CXX src/caffe/layers/prelu_layer.cpp
CXX src/caffe/layers/slice_layer.cpp
CXX src/caffe/layers/recurrent_layer.cpp
CXX src/caffe/layers/multinomial_logistic_loss_layer.cpp
CXX src/caffe/layers/argmax_layer.cpp
CXX src/caffe/layers/euclidean_loss_layer.cpp
CXX src/caffe/layers/eltwise_layer.cpp
CXX src/caffe/layers/data_layer.cpp
CXX src/caffe/layers/absval_layer.cpp
CXX src/caffe/layers/sigmoid_layer.cpp
CXX src/caffe/layers/parameter_layer.cpp
CXX src/caffe/layers/exp_layer.cpp
CXX src/caffe/layers/base_conv_layer.cpp
CXX src/caffe/layers/contrastive_loss_layer.cpp
CXX src/caffe/layers/batch_norm_layer.cpp
CXX src/caffe/layers/lstm_layer.cpp
CXX src/caffe/layers/rnn_layer.cpp
CXX src/caffe/layers/elu_layer.cpp
CXX src/caffe/layers/split_layer.cpp
CXX src/caffe/layers/hdf5_output_layer.cpp
CXX src/caffe/layers/threshold_layer.cpp
CXX src/caffe/layers/relu_layer.cpp
CXX src/caffe/layers/bnll_layer.cpp
CXX src/caffe/layers/ocl_inner_product_hwcn_layer.cpp
CXX src/caffe/layers/hdf5_data_layer.cpp
CXX src/caffe/layers/image_data_layer.cpp
src/caffe/layers/image_data_layer.cpp: In member function ‘void caffe::ImageDataLayer<Dtype>::load_batch(caffe::Batch<Dtype>*) [with Dtype = float]’:
src/caffe/layers/image_data_layer.cpp:176:1:   instantiated from here
src/caffe/layers/image_data_layer.cpp:122:13: warning: unused variable ‘crop_size’ [-Wunused-variable]
src/caffe/layers/image_data_layer.cpp: In member function ‘void caffe::ImageDataLayer<Dtype>::load_batch(caffe::Batch<Dtype>*) [with Dtype = double]’:
src/caffe/layers/image_data_layer.cpp:176:1:   instantiated from here
src/caffe/layers/image_data_layer.cpp:122:13: warning: unused variable ‘crop_size’ [-Wunused-variable]
CXX src/caffe/layers/mvn_layer.cpp
CXX src/caffe/layers/cudnn_lrn_layer.cpp
CXX src/caffe/layers/filter_layer.cpp
CXX src/caffe/layers/concat_layer.cpp
CXX src/caffe/layers/embed_layer.cpp
CXX src/caffe/layers/reshape_layer.cpp
CXX src/caffe/layers/lrn_layer.cpp
CXX src/caffe/layers/dummy_data_layer.cpp
CXX src/caffe/layers/pad_layer.cpp
CXX src/caffe/layers/scale_layer.cpp
CXX src/caffe/layers/neuron_layer.cpp
CXX src/caffe/layers/hinge_loss_layer.cpp
CXX src/caffe/layers/deconv_layer.cpp
CXX src/caffe/layers/batch_reindex_layer.cpp
CXX src/caffe/layers/cudnn_tanh_layer.cpp
CXX src/caffe/layers/im2col_layer.cpp
CXX src/caffe/layers/memory_data_layer.cpp
CXX src/caffe/layers/cudnn_lcn_layer.cpp
CXX src/caffe/layers/inner_product_layer.cpp
CXX src/caffe/layers/power_layer.cpp
CXX src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp
CXX src/caffe/layers/spp_layer.cpp
CXX src/caffe/layers/tanh_layer.cpp
CXX src/caffe/layers/cudnn_softmax_layer.cpp
CXX src/caffe/layers/pooling_layer.cpp
CXX src/caffe/layers/cudnn_sigmoid_layer.cpp
CXX src/caffe/layers/lstm_unit_layer.cpp
CXX src/caffe/layers/infogain_loss_layer.cpp
CXX src/caffe/layers/ocl_pooling_hwcn_layer.cpp
CXX src/caffe/layers/cudnn_conv_layer.cpp
CXX src/caffe/layers/loss_layer.cpp
CXX src/caffe/layers/ocl_cr_hwcn_layer.cpp
CXX src/caffe/layers/crop_layer.cpp
CXX src/caffe/layers/cudnn_pooling_layer.cpp
CXX src/caffe/layers/bias_layer.cpp
CXX src/caffe/layers/reduction_layer.cpp
CXX src/caffe/layers/window_data_layer.cpp
CXX src/caffe/layers/softmax_layer.cpp
CXX src/caffe/layers/accuracy_layer.cpp
CXX src/caffe/layers/conv_layer.cpp
CXX src/caffe/layers/tile_layer.cpp
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0
CXX tools/upgrade_solver_proto_text.cpp
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
CXX tools/train_net.cpp
CXX/LD -o .build_release/tools/train_net.bin
CXX tools/net_speed_benchmark.cpp
CXX/LD -o .build_release/tools/net_speed_benchmark.bin
CXX tools/upgrade_net_proto_binary.cpp
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX tools/extract_features.cpp
CXX/LD -o .build_release/tools/extract_features.bin
CXX tools/caffe.cpp
CXX/LD -o .build_release/tools/caffe.bin
CXX tools/test_net.cpp
CXX/LD -o .build_release/tools/test_net.bin
CXX tools/upgrade_net_proto_text.cpp
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
CXX tools/device_query.cpp
CXX/LD -o .build_release/tools/device_query.bin
CXX tools/compute_image_mean.cpp
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX tools/convert_imageset.cpp
CXX/LD -o .build_release/tools/convert_imageset.bin
CXX tools/finetune_net.cpp
CXX/LD -o .build_release/tools/finetune_net.bin
CXX examples/mnist/convert_mnist_data.cpp
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
CXX examples/cpp_classification/classification.cpp
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
CXX examples/siamese/convert_mnist_siamese_data.cpp
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
CXX examples/cifar10/convert_cifar_data.cpp
CXX/LD -o .build_release/examples/cifar10/convert_cifar_data.bin
```

**Comment by dicecco1** [comment] 2017-11-24 14:00
Did you compile the bandwidth test kernel and place it in the build repository? 

And yeah you have to compile the FPGA layers manually. The reason for this is that the build flow for the FPGA layers is on the order of hours so I didn't want to couple it directly with make all (especially since not all layers are necessary for execution). 

An example of running the layer.mk command would be: 

make -f layer.mk crp_layer_hwcn_cpfp SDA_FLOW=hw

SDA_FLOW is by default set to software emulation, but can also be hw_emu for hardware emulation, or hw for building the design. 

This makes the main kernel used to run the tests in the mnist, cifar10, and models/fpga_* directories. Within crp_layer_hwcn_cpfp.cpp there's also a define: OCFACT, which controls the amount of replication of processing elements along the output channels, best results are with this set to 16.

**Comment by JulyJohn** [comment] 2017-11-24 14:50
I have compile those layers in 'fpga_caffe/src/fpga_caffe/layers/' and got some xclbin like following:

```
bandwidth_local_16_cpu_emu.xclbin
cpfp_ops_cpu_emu.xclbin
cr_layer_fb_cpfp_cpu_emu.xclbin
crp_layer_hwcn_cpfp_16pegrp_cpu_emu.xclbin
crp_layer_hwcn_cpfp_2mult_cpu_emu.xclbin
crp_layer_hwcn_cpfp_2pegrp_cpu_emu.xclbin
crp_layer_hwcn_cpfp_8pegrp_cpu_emu.xclbin
crp_layer_hwcn_cpfp_cpu_emu.xclbin
crp_layer_hwcn_cpfp_fw_cpu_emu.xclbin
wcrp_layer_hwcn_cpfp_fw_cpu_emu.xclbin
```

then I place them in the ".build_release/opencl/src/caffe/layers/" as your Build Instructions says. Is it right or shall I place in another folder?

**Comment by dicecco1** [comment] 2017-11-24 14:56
Ah I forgot to mention that you should also remove the _cpu_emu from the names

**Comment by dicecco1** [comment] 2017-11-24 14:59
You'll also need the environment variable XCL_EMULATION_MODE=true set for running software or hardware emulation kernels.

**Comment by JulyJohn** [comment] 2017-11-24 15:02
@dicecco1 

I tried remove the _cpu_emu from bandwidth_local_16_cpu_emu.xclbin just now, then I run 

```
 XCL_EMULATION_MODE=true ./test_pcie_bandwidth.testbin 
```
still the same erro:

```
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from PCIeBandwidthTest/0, where TypeParam = OCLDevice<float>
[ RUN      ] PCIeBandwidthTest/0.TestSetup
[       OK ] PCIeBandwidthTest/0.TestSetup (4 ms)
[ RUN      ] PCIeBandwidthTest/0.TestBurst
[       OK ] PCIeBandwidthTest/0.TestBurst (58 ms)
[ RUN      ] PCIeBandwidthTest/0.TestBurst2
[       OK ] PCIeBandwidthTest/0.TestBurst2 (59 ms)
[ RUN      ] PCIeBandwidthTest/0.TestPadBurst
[       OK ] PCIeBandwidthTest/0.TestPadBurst (93 ms)
[ RUN      ] PCIeBandwidthTest/0.TestByChannel
[       OK ] PCIeBandwidthTest/0.TestByChannel (86 ms)
[ RUN      ] PCIeBandwidthTest/0.TestLocalBandwidth
ERROR: entry in lengths[i] is zero
Segmentation fault (core dumped)
```

so I was wondering if I place the .xclbin in the right directory?

**Comment by dicecco1** [comment] 2017-11-24 15:08
One last thing: the path to the file is hardcoded, so the test needs to be ran from the fpga_caffe directory directly. The same is true for running the training scripts too. I'll update the instructions to reflect this.

**Comment by JulyJohn** [comment] 2017-11-24 15:25
:-) thank you very much! @dicecco1 

This time, when I run "make runtest" in the fpga_caffe directory, it doesn't terminate anymore. Finally I got a test result like following：

```
[----------] Global test environment tear-down
[==========] 1136 tests from 160 test cases ran. (486058 ms total)
[  PASSED  ] 1127 tests.
[  FAILED  ] 9 tests, listed below:
[  FAILED  ] LayerFactoryTest/0.TestCreateLayer, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] LayerFactoryTest/1.TestCreateLayer, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] OCLCRHWCNLayerTest/0.TestForward3x3, where TypeParam = caffe::OCLDevice<float>
[  FAILED  ] OCLCRHWCNLayerTest/0.TestForward5x5, where TypeParam = caffe::OCLDevice<float>
[  FAILED  ] OCLCRHWCNLayerTest/0.TestForward1x1, where TypeParam = caffe::OCLDevice<float>
[  FAILED  ] CPFPConversionLayerTest/0.TestForwardToCPFP, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] CPFPConversionLayerTest/1.TestForwardToCPFP, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] OCLHWCNInnerProductLayerTest/0.TestForward, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] OCLHWCNInnerProductLayerTest/1.TestForward, where TypeParam = caffe::CPUDevice<double>

 9 FAILED TESTS
make: *** [runtest] Error 1
```

does is seem OK?

**Comment by dicecco1** [comment] 2017-11-24 15:30
Yeah that's to be expected, if you crank up the mantissa sizes in include/fpga/cpfp.hpp and recompile everything (including the kernels) these tests will pass. E.g. setting the mantissa to like 9.

**Comment by JulyJohn** [comment] 2017-11-25 12:48
Hi, @dicecco1 

I set the [MANT_SIZE](https://github.com/dicecco1/fpga_caffe/blob/master/include/fpga_caffe/cpfp.hpp#L18) to 9 as your suggestion at the first time, but the tests didn't pass.So in the next time, I change the **MANT_SIZE** to 10, It passed.

I've run the train_full_ocl_hwcn.sh in  folder **examples/cifar10**, here is my command(in the caffe root directory);

```
XCL_EMULATION_MODE=true ./examples/cifar10/train_full_ocl_hwcn.sh
```

After two hours, the first 100 iteration doesn't complete, is it to be expected?

So, I want to train it on the fpga rather than cpu_emulation, can you reproduce how to do this ?

Besides, I wish you could reproduce how to make inference on fpga using your project. :-)

**Comment by dicecco1** [comment] 2017-11-25 13:29
Yeah that's to be expected, software emulation is much much slower than running on the hardware directly.

To train directly on the FPGA you need to build the kernel for the FPGA rather than cpu emulation. To do that run this command:

make -f layer.mk crp_layer_hwcn_cpfp SDA_FLOW=hw

Also I recommend changing OCFACT to be 12,14, or 16 though build times may be 5+ hours. Once you have the kernel built it's as simple as running the script you ran before, just without the XCL_EMULATION_MODE flag set.

If you want to run inference using this setup on some bigger models take a look at the models/fpga_* directories. You'll have to download the pretrained weights and validation images and use the post processing python script in each directory, then you can use the caffe tool to classify the images in the same way as you would on a CPU, just with the flag --ocl=1 set.

**Comment by JulyJohn** [comment] 2017-11-27 02:00
Hi, @dicecco1 

Since my device is **xilinx:kcu1500:4ddr-xpr:4.0**(but I haven't installed it in the machine that I'm using now),  so I change the DSA to **xilinx:kcu1500:4ddr-xpr:4.0** in the layer.mk. Then I run command:

```
make -f layer.mk KERNEL_NAME=crp_layer_hwcn_cpfp SDA_FLOW=hw
```

I got an erro like this :

```
[root@localhost layers]# make -f layer.mk KERNEL_NAME=crp_layer_hwcn_cpfp SDA_FLOW=hw
xocc -t hw --platform xilinx:kcu1500:4ddr-xpr:4.0 --report estimate --nk crp_layer_hwcn_cpfp:1 --kernel crp_layer_hwcn_cpfp -I ../../../include/ -DSYNTHESIS -s -o crp_layer_hwcn_cpfp.xclbin crp_layer_hwcn_cpfp.cpp

****** xocc v2016.3_sdx
  **** SW Build 1721985 on Tue Nov 29 18:41:34 MST 2016
    ** Copyright 1986-2016 Xilinx, Inc. All Rights Reserved.

INFO: [XOCC 60-585] Compiling for hardware target
ERROR: [XOCC 60-780] No device found that matches xpfm file 'xilinx:kcu1500:4ddr-xpr:4.0'
ERROR: [XOCC 60-587] Failed to add a device: specified platform xilinx:kcu1500:4ddr-xpr:4.0 is not found
ERROR: [XOCC 60-598] Kernel build setup failed to complete
ERROR: [XOCC 60-702] Failed to finish compilation and linking
make: *** [crp_layer_hwcn_cpfp.xclbin] Error 1
```
Could you provide any suggestion?

**Comment by JulyJohn** [comment] 2017-11-29 13:26
hi, @dicecco1 

The Sdaccel 2016.3 does not support my device, so I change it to 2017.1. Since the 2017.1 require centos6.8, I change my OS to Centos 6.8 too.

My OCFACT is set to be 1 and mantissa size is 6. In the **fpga_caffe** directory, I run command : 

```
 ./examples/cifar10/train_full_ocl_hwcn.sh
```
and I got this erro :

```
I1129 21:04:14.156110  4016 solver.cpp:330] Iteration 0, Testing net (#0)
WARNING: unaligned host pointer detected, this leads to extra memcpy
.....many warnings......
WARNING: unaligned host pointer detected, this leads to extra memcpy
I1129 21:04:39.156116  4026 data_layer.cpp:73] Restarting data prefetching from start.
I1129 21:04:41.912981  4016 solver.cpp:397]     Test net output #0: accuracy = 0.0914062
I1129 21:04:41.913027  4016 solver.cpp:397]     Test net output #1: loss = 2.3026 (* 1 = 2.3026 loss)
ERROR: some device is already programmed
ERROR: program is nullptr
WARNING: unaligned host pointer detected, this leads to extra memcpy
.....many warnings......
WARNING: unaligned host pointer detected, this leads to extra memcpy
*** Aborted at 1511960681 (unix time) try "date -d @1511960681" if you are using GNU date ***
PC: @     0x7f06edc10532 clSetKernelArg
*** SIGSEGV (@0x48) received by PID 4016 (TID 0x7f06f0f75960) from PID 72; stack trace: ***
    @     0x7f06ec9557e0 (unknown)
    @     0x7f06edc10532 clSetKernelArg
    @     0x7f06f0979b61 caffe::OCLCRHWCNLayer<>::launchKernel()
    @     0x7f06f097a98a caffe::OCLCRHWCNLayer<>::Forward_ocl()
    @     0x7f06f0a9ecd3 caffe::Net<>::ForwardFromTo()
    @     0x7f06f0a9ef1f caffe::Net<>::Forward()
    @     0x7f06f09373af caffe::Solver<>::Step()
    @     0x7f06f0937dd5 caffe::Solver<>::Solve()
    @           0x40a43a train()
    @           0x40d67f main
    @     0x7f06ec5d0d1d __libc_start_main
    @           0x406f79 (unknown)
./examples/cifar10/train_full_ocl_hwcn.sh: line 7:  4016 Segmentation fault      (core dumped) $TOOLS/caffe train --solver=examples/cifar10/cifar10_full_solver_ocl_hwcn.prototxt $@ --ocl=1
```

As you can see, there are so many warnings like "unaligned host pointer detected, this leads to extra memcpy", and I am curious about it. Besides, it also occurs when I do the (inference)[https://github.com/dicecco1/fpga_caffe/tree/master/examples/cpp_classification], although the inference process finally works fine.

As for the erro, could you provide some suggestions?

**Comment by dicecco1** [comment] 2017-11-29 13:32
Hmm that's really weird, I haven't seen that before (though I've only ran a couple times using 2017.1). Does the error happen in the individual FPGA tests?

**Comment by JulyJohn** [comment] 2017-11-30 01:49
@dicecco1 

Yeah, same error occurs when in the FPGA test, and here is the detailed log : 

```
[root@fpga fpga_caffe]# ./build/testfpga/test_crp_fc_hwcn_cpfp.testbin 
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from CRPFCHWCNCPFPTest/0, where TypeParam = OCLDevice<float>
[ RUN      ] CRPFCHWCNCPFPTest/0.TestFCReLU1x1F_CPFP
0 0 relu: 0
0 0 relu: 0
0 0 relu: 0
...
...some failure due to 'Value of: checkEQ(this->sw_results[j], this->hw_results[j], 1e-1, 1e-1)'...
...
0.543429 0.46875 relu: 1
0 0 relu: 0
0.391912 0.375 relu: 1
0 0 relu: 0
0 0 relu: 0
[  FAILED  ] CRPFCHWCNCPFPTest/0.TestFCReLU1x1F_CPFP, where TypeParam = OCLDevice<float> (279 ms)
[ RUN      ] CRPFCHWCNCPFPTest/0.TestFCReLU1x1B_CPFP
ERROR: some device is already programmed
ERROR: program is nullptr
ERROR: program is nullptr
Segmentation fault (core dumped)
```

**Comment by JulyJohn** [comment] 2017-12-01 01:57
hi, @dicecco1 

I found that this error might come from that you didn't release the program or kernel after them have been executed, and a previous issue in https://github.com/dicecco1/fpga_caffe/issues/3#issuecomment-321729610 already has mentioned it. 

Maybe it's caused by the new version sdaccel, but it really seems like a actual bug to fix.

**Comment by dicecco1** [comment] 2017-12-01 02:15
I agree that it's probably due to the newer version of SDAccel, I'm just not sure what's causing the segfault though. The error due to clBuildProgram is fixed in the actual flow, I forgot to remove it from the test flow though so that should be a quick fix. 

I'm more curious about the unaligned host pointer error that you saw than these SDAccel specific errors though. It's hard to fix the SDAccel errors because with every new release different problems come up (SDaccel in 2015 looked much different than it does now).

**Comment by JulyJohn** [comment] 2017-12-01 02:26
thanks, @dicecco1 

"unaligned host pointer detected, this leads to extra memcpy" is a warning rather an error.

According to an [question](https://stackoverflow.com/questions/13881487/should-i-worry-about-the-alignment-during-pointer-casting) in stackflow it's likely due to that we should use memcpy function in a more normal way.

**Comment by dicecco1** [comment] 2017-12-01 02:34
Ah okay, that's good to know, it might be because of the way I'm using the CPFP types in Caffe. It's sort of hacky but easier to get the flow working by dynamic casting the floating point variables to CPFP and transferring half the data. 

But you did see that segfault while training too, which is pretty strange, it looks like it's being caused by clSetKernelArg which is pretty weird.

**Comment by JulyJohn** [comment] 2017-12-01 02:38
@dicecco1 
I'm wondering if the error will disappear after we overcome the “**ERROR: some device is already programmed
ERROR: program is nullptr**” erro?

**Comment by dicecco1** [comment] 2017-12-04 04:16
Is it after only one iteration?

**Comment by JulyJohn** [comment] 2017-12-04 04:31
@dicecco1 

after the test process in the initialization when it comes to the first 200 iteration train process.

**Comment by dicecco1** [comment] 2017-12-05 02:38
Hmm that's interesting, not sure what your schedule is like, but if you have time could you try commenting out the "once: true" setting in the XCLProgram layer. This will make execution a lot slower because it'll reprogram the device after every iteration (roughly 10s), but I'm wondering if this might fix it (if so this might be an SDAccel problem).

**Comment by JulyJohn** [comment] 2017-12-05 03:57
thank you! @dicecco1 

I think I might have solved the problem after add clReleaseProgram() and clReleaseKernel() at https://github.com/dicecco1/fpga_caffe/blob/bca2e86cf2a794042393179af6439564757b94f2/src/caffe/layers/XCL_program_layer.cpp#L23 .

but during the training it throw out so many errors like following(although the training process doesn't terminate): 

```
ERROR: offset+size > mem size
``` 

any suggestion?

**Comment by dicecco1** [comment] 2017-12-05 04:05
Can you give the full error?

**Comment by JulyJohn** [comment] 2017-12-05 06:55
sorry for the delay. :-) @dicecco1 

the log is just like this:

```
....
I1205 11:43:40.179606  8001 solver.cpp:397]     Test net output #0: accuracy = 0.0889648
I1205 11:43:40.179653  8001 solver.cpp:397]     Test net output #1: loss = 2.30251 (* 1 = 2.30251 loss)
WARNING: unaligned host pointer detected, this leads to extra memcpy
WARNING: unaligned host pointer detected, this leads to extra memcpy
.......
WARNING: unaligned host pointer detected, this leads to extra memcpy
I1205 11:43:42.246222  8001 solver.cpp:218] Iteration 0 (-6.43965e-40 iter/s, 29.82s/100 iters), loss = 2.30245
I1205 11:43:42.246285  8001 solver.cpp:237]     Train net output #0: loss = 2.30245 (* 1 = 2.30245 loss)
I1205 11:43:42.246309  8001 sgd_solver.cpp:105] Iteration 0, lr = 0.001
ERROR: offset+size > mem size
.......
ERROR: offset+size > mem size
I1205 11:46:48.265085  8001 solver.cpp:218] Iteration 100 (0.537582 iter/s, 186.018s/100 iters), loss = 1.94949
I1205 11:46:48.265259  8001 solver.cpp:237]     Train net output #0: loss = 1.94949 (* 1 = 1.94949 loss)
I1205 11:46:48.265276  8001 sgd_solver.cpp:105] Iteration 100, lr = 0.001
ERROR: offset+size > mem size
ERROR: offset+size > mem size
....
```
and the warnings("WARNING: unaligned host pointer detected, this leads to extra memcpy") only appear at the beginning , the errors appear in every ocl layer in every iteration.

**Comment by JulyJohn** [comment] 2017-12-19 13:43
hi, @dicecco1 

Recently I try to run your project in debug mode, and I finally find that the error "**ERROR: offset+size > mem size**" was caused by "**bottom[0]->mutable_cpu_diff()**" at https://github.com/dicecco1/fpga_caffe/blob/a7d524bb7ce3e3afb663e5b855b78589e7827306/src/caffe/layers/ocl_pooling_hwcn_layer.cpp#L237-L238.

More exactly, I set a breakpoint at that line, and the process comes to that line(I'm sure that line hasn't been executed yet), then I try to add a watch "**bottom[0]->mutable_cpu_diff()**" in the IDE, the error comes out.

Any suggestion?

**Comment by dicecco1** [comment] 2017-12-20 03:02
Actually that line of code isn't even necessary, just a fragment from before some optimizations got made that somehow made it through. It's just deadcode so I've deleted it for you so if you get the latest change it should be fixed.

**Closed as completed** 2018-06-05 09:28 UTC

**Comment by louvinci** [comment] 2019-05-25 00:53
Sorry to bother you. I have a problem.
when i run the "./.build_release/testfpga/test_pcie_bandwidth.testbin" 
There are following ERRORs

```
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from PCIeBandwidthTest/0, where TypeParam = OCLDevice<float>
[ RUN      ] PCIeBandwidthTest/0.TestSetup
[       OK ] PCIeBandwidthTest/0.TestSetup (1 ms)
[ RUN      ] PCIeBandwidthTest/0.TestBurst
[       OK ] PCIeBandwidthTest/0.TestBurst (106 ms)
[ RUN      ] PCIeBandwidthTest/0.TestBurst2
[       OK ] PCIeBandwidthTest/0.TestBurst2 (83 ms)
[ RUN      ] PCIeBandwidthTest/0.TestPadBurst
[       OK ] PCIeBandwidthTest/0.TestPadBurst (141 ms)
[ RUN      ] PCIeBandwidthTest/0.TestByChannel
[       OK ] PCIeBandwidthTest/0.TestByChannel (115 ms)
[ RUN      ] PCIeBandwidthTest/0.TestLocalBandwidth
ERROR: bad binary version 'PK
ERROR: program is nullptr
ERROR: program is nullptr
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
Segmentation fault (core dumped)
```


I have placed the fpga_caffe/src/fpga_caffe/layers/*.xclbin(already removed the _cpu_emu from the names) 
in the ".build_release/opencl/src/caffe/layers/" and set the environment(XCL_EMULATION_MODE=true)

Are there any mistakes in my previous steps?
The command I run is 
1. Make all
2. Make test
3. Make testfpga
4. Compile the FPGA layers manually and place them in the right place
5. set the environment
6. ./*testbin
I have no idea about this mistake. Do you have any suggestions?
Hope for your reply!
